### ISSUE TITLE
Fatal Non-UI Error: missing file

### ISSUE THREAD

**Issue by Magmahunter** [KartKrewDev/High-Voltage-Ring#1]
Trying to boot HVR instantly throws up the following error:
Can't find file UDBuilder.default.cfg

**Comment by MaxFirestorm** [comment]
Seconding the issue.

**Comment by MaxFirestorm** [comment]
Apparently the fix is to go to the directory where High Voltage Ring was instaled and rename "HVRBuilder.default.cfg" to "UDBuilder.default.cfg
